baseURL = 'https://u-yuta.com/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'u-yuta'
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
[markup.goldmark.renderer]
  unsafe = true
[params]
  [params.homeInfoParams]
    Title = "Hi there"
    Content = "Can be Info, links, about..."
[taxonomies]
  tag = "tags"
  category = "categories"
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 20
[[menus.main]]
    name = 'tags'
    pageRef = '/tags'
    weight = 30
[[menus.main]]
    name = 'categories'
    pageRef = '/categories'
    weight = 40