#+hugo_base_dir: ../
#+title: u-yuta
#+author: u-yuta


* blog
** DONE Windows WSLでのPython環境構築メモ 2
CLOSED: [2024-04-15 Mon 22:41]
:PROPERTIES:
:EXPORT_FILE_NAME: python-on-wsl-environment-setup-memo-2
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowToc true
:END:

[[Windows WSLでのPython環境構築メモ 1][Windows WSLでのPython環境構築メモ 1]] 続き

*** 方針： Jupyter での仮想環境の利用
Jupyterは基本的にベース環境にのみインストールする。

仮想環境ごとにJupyterをインストールすると次のような問題が出るため。
- 仮想環境ごとにJupyter, JupyterLab, ... をインストールする必要があり、手間とディスク容量がかかる。
- プロジェクトを切り替えるたびにJupyterLabを起動し直したり、JupyterLab上でのルートフォルダ
  の場所が変わるのでファイルを開き直したりする必要がある。

プロジェクトごとの仮想環境のカーネルをJupyterに登録し（ipykernel）
JupyterLabの起動ディレクトリを常に同じ場所に保つことで、上記の問題が避けられる。

**** 例外
JupyterにPythonカーネルを登録しても、Pythonの管理外のプログラムへのパスが通らない。
そのためcondaで仮想環境を作った場合で仮想環境にPython以外のプログラムが含まれる場合は、
上記の方法だとJupyter上でのプログラムの動作に支障が出る。

そのような場合はcondaの仮想環境にJupyterをインストールして使う。

*** ipynbファイルのバージョン（Git）管理
Jupytextでpy-script化したものをGit管理する。ipynbファイル自体をGit管理すると
実行状態によって差分が出て管理がしづらいため。

** DONE Windows WSLでのPython環境構築メモ 1                       :python:
CLOSED: [2024-04-14 Sun 16:29]
:PROPERTIES:
:EXPORT_FILE_NAME: python-on-wsl-environment-setup-memo-1
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :ShowToc true
:ID:       python-on-wsl-environment-setup-memo-1
:END:

WSL上でのPython環境構築に関するメモ。ここでは方針のみ。具体的な手順は後ほど追加する。
*** 前提
Pythonの用途は、データ解析と統計処理・可視化、物理・工学の計算機シミュレーション、数式処理など。

主な使用パッケージはNumpy, Scipy, Pandas, Matplotlib, Holoviz (hvPlot, Panel), etc.
   
*** 方針： ベース環境
システムのPython（OSが使用するPython）とは別に、「ベース環境」として普段使い用のPython環境をインストールする。

必要に応じてバージョンが切り替えられるように、ベース環境は [[https://asdf-vm.com][asdf]] を用いてインストールする。
後述する仮想環境を有効にしていない限りは、シェルの ~python~ コマンドでベース環境のPythonが実行される。
 
*** 方針: 仮想環境
Python本体や使用ライブラリのバージョン違いによる不具合を避けて再現性を保つため、プロジェクトごとに実行環境（仮想環境）を作って管理する。

VSCodeで自動的に認識されるように、仮想環境はプロジェクトのrootディレクトリの ~.venv/~ にインストールする。

[[Windows WSLでのPython環境構築メモ 2][Windows WSLでのPython環境構築メモ 2]] へ続く。
